use shfmt and format sources

diff --git a/.github/workflows/gt-update.yml b/.github/workflows/gt-update.yml
--- a/.github/workflows/gt-update.yml
+++ b/.github/workflows/gt-update.yml
@@ -39,21 +39,28 @@ jobs:
         run: |
           set -e
           # see install.doc.sh in https://github.com/tegonal/gt, MODIFY THERE NOT HERE (please report bugs)
-          currentDir=$(pwd) && \
-          tmpDir=$(mktemp -d -t gt-download-install-XXXXXXXXXX) && cd "$tmpDir" && \
-          wget "https://raw.githubusercontent.com/tegonal/gt/main/.gt/signing-key.public.asc" && \
-          wget "https://raw.githubusercontent.com/tegonal/gt/main/.gt/signing-key.public.asc.sig" && \
-          gpg --verify ./signing-key.public.asc.sig ./signing-key.public.asc && \
-          echo "public key trusted" && \
-          mkdir ./gpg && \
-          gpg --homedir ./gpg --import ./signing-key.public.asc && \
-          wget "https://raw.githubusercontent.com/tegonal/gt/v1.4.4/install.sh" && \
-          wget "https://raw.githubusercontent.com/tegonal/gt/v1.4.4/install.sh.sig" && \
-          gpg --homedir ./gpg --verify ./install.sh.sig ./install.sh && \
-          chmod +x ./install.sh && \
-          echo "verification successful" || (printf >&2 "\033[0;31mERROR\033[0m: verification failed, don't continue !!\n"; exit 1) && \
-          ./install.sh && result=true || (echo >&2 "installation failed"; exit 1) && \
-          false || cd "$currentDir" && rm -r "$tmpDir" && "${result:-false}"
+          #!/usr/bin/env bash
+          currentDir=$(pwd) &&
+          	tmpDir=$(mktemp -d -t gt-download-install-XXXXXXXXXX) && cd "$tmpDir" &&
+          	wget "https://raw.githubusercontent.com/tegonal/gt/main/.gt/signing-key.public.asc" &&
+          	wget "https://raw.githubusercontent.com/tegonal/gt/main/.gt/signing-key.public.asc.sig" &&
+          	gpg --verify ./signing-key.public.asc.sig ./signing-key.public.asc &&
+          	echo "public key trusted" &&
+          	mkdir ./gpg &&
+          	gpg --homedir ./gpg --import ./signing-key.public.asc &&
+          	wget "https://raw.githubusercontent.com/tegonal/gt/v1.4.4/install.sh" &&
+          	wget "https://raw.githubusercontent.com/tegonal/gt/v1.4.4/install.sh.sig" &&
+          	gpg --homedir ./gpg --verify ./install.sh.sig ./install.sh &&
+          	chmod +x ./install.sh &&
+          	echo "verification successful" ||
+          	{
+          		printf >&2 "\033[0;31mERROR\033[0m: verification failed, don't continue !!\n"
+          		exit 1
+          	} && ./install.sh && result=true ||
+          	{
+          		echo >&2 "installation failed"
+          		exit 1
+          	} && false || cd "$currentDir" && rm -r "$tmpDir" && "${result:-false}"
           # end install.doc.sh
       - uses: actions/checkout@v5
       - id: set-matrix
@@ -78,21 +85,28 @@ jobs:
         run: |
           set -e
           # see install.doc.sh in https://github.com/tegonal/gt, MODIFY THERE NOT HERE (please report bugs)
-          currentDir=$(pwd) && \
-          tmpDir=$(mktemp -d -t gt-download-install-XXXXXXXXXX) && cd "$tmpDir" && \
-          wget "https://raw.githubusercontent.com/tegonal/gt/main/.gt/signing-key.public.asc" && \
-          wget "https://raw.githubusercontent.com/tegonal/gt/main/.gt/signing-key.public.asc.sig" && \
-          gpg --verify ./signing-key.public.asc.sig ./signing-key.public.asc && \
-          echo "public key trusted" && \
-          mkdir ./gpg && \
-          gpg --homedir ./gpg --import ./signing-key.public.asc && \
-          wget "https://raw.githubusercontent.com/tegonal/gt/v1.4.4/install.sh" && \
-          wget "https://raw.githubusercontent.com/tegonal/gt/v1.4.4/install.sh.sig" && \
-          gpg --homedir ./gpg --verify ./install.sh.sig ./install.sh && \
-          chmod +x ./install.sh && \
-          echo "verification successful" || (printf >&2 "\033[0;31mERROR\033[0m: verification failed, don't continue !!\n"; exit 1) && \
-          ./install.sh && result=true || (echo >&2 "installation failed"; exit 1) && \
-          false || cd "$currentDir" && rm -r "$tmpDir" && "${result:-false}"
+          #!/usr/bin/env bash
+          currentDir=$(pwd) &&
+          	tmpDir=$(mktemp -d -t gt-download-install-XXXXXXXXXX) && cd "$tmpDir" &&
+          	wget "https://raw.githubusercontent.com/tegonal/gt/main/.gt/signing-key.public.asc" &&
+          	wget "https://raw.githubusercontent.com/tegonal/gt/main/.gt/signing-key.public.asc.sig" &&
+          	gpg --verify ./signing-key.public.asc.sig ./signing-key.public.asc &&
+          	echo "public key trusted" &&
+          	mkdir ./gpg &&
+          	gpg --homedir ./gpg --import ./signing-key.public.asc &&
+          	wget "https://raw.githubusercontent.com/tegonal/gt/v1.4.4/install.sh" &&
+          	wget "https://raw.githubusercontent.com/tegonal/gt/v1.4.4/install.sh.sig" &&
+          	gpg --homedir ./gpg --verify ./install.sh.sig ./install.sh &&
+          	chmod +x ./install.sh &&
+          	echo "verification successful" ||
+          	{
+          		printf >&2 "\033[0;31mERROR\033[0m: verification failed, don't continue !!\n"
+          		exit 1
+          	} && ./install.sh && result=true ||
+          	{
+          		echo >&2 "installation failed"
+          		exit 1
+          	} && false || cd "$currentDir" && rm -r "$tmpDir" && "${result:-false}"
           # end install.doc.sh
       - uses: actions/checkout@v5
       - name: reset gpg keys
