check if signing key already are or will expire within the next 3 months

diff --git a/.github/workflows/gt-update.yml b/.github/workflows/gt-update.yml
--- a/.github/workflows/gt-update.yml
+++ b/.github/workflows/gt-update.yml
@@ -134,23 +134,34 @@ jobs:
       - uses: actions/checkout@v4
       - name: check if signing key already are or will expire within the next 3 months
         run: |
+          set -euo pipefail
           currentDir="$(pwd)"
           signingKey=".gt/signing-key.public.asc"
           if ! [[ -f "$currentDir/$signingKey" ]]; then
             echo "$signingKey does not exist in this repo"
-          else
-            set -e
-            tmpDir=$(mktemp -d -t gt-check-gpg-XXXXXXXXXX)
-            cd "$tmpDir"
-            gpg --homedir . --import "$currentDir/$signingKey"
-            expired=0
-            while read -r key; do
-              expirationDate=$(cut -d ':' -f7 <<<"$key")
-              echo "expirationDate: $expirationDate"
-              if (( $expirationDate < $(date -d "+1 year" +%s) )); then
-                echo >&2 "expiration date $(date -d "@$((expirationDate + 0))" +%s) of key $key"
-                ((++expired))
-              fi
-            done < <(gpg --homedir . --list-keys --list-options show-unusable-subkeys --with-colons | grep '^pub')
-            [[ expired -eq 0 ]]
+            return 0
           fi
+
+          tmpDir=$(mktemp -d -t gt-check-gpg-XXXXXXXXXX)
+          cd "$tmpDir"
+          gpg --homedir . --import "$currentDir/$signingKey"
+
+
+          limitTimestamp=$(date -d "+1 year" +%s)
+          limitDate=$(date -d "@$limitTimestamp" +"%Y-%m-%dT%H:%M:%S")
+          echo "checking if the following public keys defined in $signingKey are valid until $limitDate"
+          gpg --homedir . --list-keys --list-options show-unusable-subkeys --keyid-format LONG
+          echo ""
+
+          expired=0
+          while read -r key; do
+            keyId=$(cut -d ':' -f5 <<<"$key")
+            expirationTimestamp=$(cut -d ':' -f7 <<<"$key")
+            if (( expirationTimestamp < $limitTimestamp )); then
+              expirationDate=$(date -d "@$((expirationTimestamp + 0))" +"%Y-%m-%dT%H:%M:%S")
+              printf >&2 "\033[0;31mERROR\033[0m: expiration date (%s) of key %s before the given limit %s\n" "$expirationDate" "$keyId" "$limitDate"
+              ((++expired))
+            fi
+          done < <(gpg --homedir . --list-keys --list-options show-unusable-subkeys --with-colons | grep '^pub')
+          [[ $expired -eq 0 ]]
+
